version: 2.1

jobs:
  analyze:
    docker:
      - image: 'cimg/openjdk:21.0.8'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar -DskipTests
  test:
    executor: machine_executor_amd64
    steps:
      - checkout
      - run:
          name: Maven Tests
          command: mvn test

executors:
  machine_executor_amd64:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@2.1.0

workflows:
  maven_test:
    jobs:
      - test
      - analyze:
          context: SonarCloud